"""Property R-PROP-005: CBT budget-balance.

The cost-benefit-transfer module distributes the surplus generated by
coordination among participants. For every feasible UtilityLedger:

1. `sum(transfers) == surplus` — the full surplus is distributed, no
   slack created or destroyed.
2. `after_transfer[pid] == local[pid] + transfers[pid]` for every
   participant — per-participant accounting is consistent.

`surplus` is `global_utility - sum(outside_options)`. CBT does not
implement zero-sum redistribution among existing utilities; it
distributes the gain from coordination above the walk-away baseline.

Per DEC-PROP-001: budget-balance is a property of `engine/cbt.py`
specifically. Mechanisms that produce the ledger CBT consumes are
exercised via the centralized oracle generator below.
"""

from __future__ import annotations

from hypothesis import given, settings

from procurement_lab.algorithms.oracle import CentralizedOracle
from procurement_lab.engine.cbt import compute_transfer
from procurement_lab.engine.schemas import (
    AlgorithmRun,
    Convergence,
    Scenario,
)
from tests.property.conftest import scenario_strategy

BUDGET_BALANCE_TOLERANCE = 1e-6


@given(scenario=scenario_strategy())
@settings(max_examples=40)
def test_proportional_split_distributes_full_surplus(scenario: Scenario) -> None:
    """sum(transfers) equals surplus; after_transfer matches local + transfer per participant."""
    run: AlgorithmRun = CentralizedOracle().run(scenario)

    if run.convergence == Convergence.NO_DEAL or not run.ledger.feasible:
        return

    plan = compute_transfer(run.ledger, rule="proportional")

    if not plan.feasible:
        return

    transfer_sum = sum(plan.transfers.values())
    expected_distribution = plan.surplus
    assert abs(transfer_sum - expected_distribution) <= BUDGET_BALANCE_TOLERANCE, (
        f"proportional CBT transfers ({transfer_sum:.6f}) do not match "
        f"surplus ({expected_distribution:.6f})"
    )

    # Per-participant accounting: after_transfer[pid] == local[pid] + transfers[pid]
    for pid in plan.transfers:
        local = run.ledger.local[pid]
        transfer = plan.transfers[pid]
        after = plan.after_transfer[pid]
        assert abs((local + transfer) - after) <= BUDGET_BALANCE_TOLERANCE, (
            f"participant {pid}: after_transfer ({after:.6f}) != "
            f"local ({local:.6f}) + transfer ({transfer:.6f})"
        )


@given(scenario=scenario_strategy())
@settings(max_examples=40)
def test_equal_split_distributes_full_surplus(scenario: Scenario) -> None:
    """Equal-split rule satisfies the same distribution invariants."""
    run: AlgorithmRun = CentralizedOracle().run(scenario)

    if run.convergence == Convergence.NO_DEAL or not run.ledger.feasible:
        return

    plan = compute_transfer(run.ledger, rule="equal")

    if not plan.feasible:
        return

    transfer_sum = sum(plan.transfers.values())
    expected_distribution = plan.surplus
    assert abs(transfer_sum - expected_distribution) <= BUDGET_BALANCE_TOLERANCE, (
        f"equal CBT transfers ({transfer_sum:.6f}) do not match "
        f"surplus ({expected_distribution:.6f})"
    )

    for pid in plan.transfers:
        local = run.ledger.local[pid]
        transfer = plan.transfers[pid]
        after = plan.after_transfer[pid]
        assert abs((local + transfer) - after) <= BUDGET_BALANCE_TOLERANCE, (
            f"participant {pid}: after_transfer ({after:.6f}) != "
            f"local ({local:.6f}) + transfer ({transfer:.6f})"
        )
