"""Cost-benefit transfer (CBT) — split surplus among participants.

Given a UtilityLedger, compute the surplus generated by coordination vs every
participant's outside option, then split it so every participant ends up
no-worse-off if feasible. If infeasible (the surplus can't make every
participant whole), return a transfer plan flagged infeasible with a note —
do not silently force a settlement.

The default split is proportional to outside-option deficit: participants
who would have lost more if they walked away get more of the surplus. This
is a simple, defensible Nash-bargaining-style rule for v0; the lab can
expose other splits (equal, Shapley, etc.) in v1.
"""

from __future__ import annotations

from procurement_lab.engine.schemas import TransferPlan, UtilityLedger


def compute_transfer(
    ledger: UtilityLedger,
    *,
    rule: str = "proportional",
) -> TransferPlan:
    """Compute the surplus-split transfer plan.

    Rules:
        proportional   each participant's gain = surplus * their_outside_deficit / total_deficit
        equal          surplus split evenly across participants
    """

    participant_ids = list(ledger.local.keys())
    n = len(participant_ids)

    total_outside = sum(ledger.outside_options.values())
    surplus = ledger.global_utility - total_outside

    if surplus < 0:
        # Coordination produces less than the sum of outside options.
        # No transfer can make all parties whole.
        return TransferPlan(
            transfers={pid: 0.0 for pid in participant_ids},
            after_transfer=dict(ledger.local),
            surplus=surplus,
            no_worse_off={
                pid: ledger.local[pid] >= ledger.outside_options[pid]
                for pid in participant_ids
            },
            feasible=False,
            note=(
                f"surplus is negative (${surplus:.2f}); coordination is worse "
                "than walk-away. No transfer can make all parties whole."
            ),
        )

    if rule == "equal":
        per_share = surplus / n
        gains = {pid: per_share for pid in participant_ids}
    elif rule == "proportional":
        # weight by how much each participant fell short of their outside option
        # if everyone is already above outside, weight by 1/n
        deficits = {
            pid: max(0.0, ledger.outside_options[pid] - ledger.local[pid])
            for pid in participant_ids
        }
        total_deficit = sum(deficits.values())
        if total_deficit == 0:
            # everyone is already at or above outside option; split equally
            per_share = surplus / n
            gains = {pid: per_share for pid in participant_ids}
        else:
            gains = {
                pid: surplus * (deficits[pid] / total_deficit) for pid in participant_ids
            }
    else:
        raise ValueError(f"unknown rule: {rule!r}")

    transfers: dict[str, float] = {}
    after_transfer: dict[str, float] = {}
    no_worse_off: dict[str, bool] = {}
    for pid in participant_ids:
        # transfer = gain (signed; positive = participant receives)
        transfers[pid] = gains[pid]
        after_transfer[pid] = ledger.local[pid] + gains[pid]
        no_worse_off[pid] = after_transfer[pid] >= ledger.outside_options[pid] - 1e-6

    feasible = all(no_worse_off.values())
    note = (
        f"split rule: {rule}; surplus ${surplus:.2f}"
        if feasible
        else (
            f"split rule: {rule}; surplus ${surplus:.2f} but at least one "
            "participant remains below their outside option."
        )
    )

    return TransferPlan(
        transfers=transfers,
        after_transfer=after_transfer,
        surplus=surplus,
        no_worse_off=no_worse_off,
        feasible=feasible,
        note=note,
    )
